version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    tty: true


volumes:
  node_modules:
